# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e1b100a6e6c80a6ff1049378c8c1b97acb9ab3c6b402da545e3475802a0e007ee14bcaa71ae4b249e853a2d25f35b94518adf2d08ed567ab3941a816d1be274

test:
  secret_key_base: 34ecdf513cd11b874d91c2a66e6101b2ab9d33a8a8e9671dbcbe2be0e8d4c68c1a0097c7dfe85960b54384b7358ce859006e9f1895001e415db38ff378e65356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
